export const API_PATH = "https://api.themoviedb.org";
export const API_KEY = "085cb25db7a6157ba344e23d3bfc9f23";
export const IMAGE_PATH = "https://image.tmdb.org/t/p/original"

export const ACTION_TYPE = {
    DISCOVER_FILMS_REQUEST: "DISCOVER_FILMS_REQUEST",
    DISCOVER_FILMS_RESPONSE_SUCCESS: "DISCOVER_FILMS_RESPONSE_SUCCESS",
    DISCOVER_FILMS_RESPONSE_FAILURE: "DISCOVER_FILMS_RESPONSE_FAILURE",
    GENRES_REQUEST: "GENRES_REQUEST",
    GENRES_RESPONSE_SUCCESS: "GENRES_RESPONSE_SUCCESS",
    GENRES_RESPONSE_FAILURE: "GENRES_RESPONSE_FAILURE"
}
