export const API_PATH = "https://api.themoviedb.org";
// API_KEY left in for testing, to be moved to an external file
export const API_KEY = "085cb25db7a6157ba344e23d3bfc9f23";
export const IMAGE_PATH = "https://image.tmdb.org/t/p/w154"

export const ACTION_TYPE = {
    DISCOVER_FILMS_REQUEST: "DISCOVER_FILMS_REQUEST",
    DISCOVER_FILMS_RESPONSE_SUCCESS: "DISCOVER_FILMS_RESPONSE_SUCCESS",
    DISCOVER_FILMS_RESPONSE_FAILURE: "DISCOVER_FILMS_RESPONSE_FAILURE",
    GENRES_REQUEST: "GENRES_REQUEST",
    GENRES_RESPONSE_SUCCESS: "GENRES_RESPONSE_SUCCESS",
    GENRES_RESPONSE_FAILURE: "GENRES_RESPONSE_FAILURE",
    SEARCH_REQUEST: "SEARCH_REQUEST",
    SEARCH_RESPONSE_SUCCESS: "SEARCH_RESPONSE_SUCCESS",
    SEARCH_RESPONSE_FAILURE: "SEARCH_RESPONSE_FAILURE"
}
